irc_bot/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'irc_bot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'irc_bot.bot.views.logPage'),
    url(r'^admin/', include(admin.site.urls)),
)

irc_bot/bot/models.py
from django.db import models

# Create your models here.

class main(models.Model):
    channel = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=100, null=True)
    time = models.DateTimeField()
    message = models.TextField(null=True)
    type = models.CharField(max_length=20, null=True)
    hidden = models.CharField(max_length=2)

    def __unicode__(self):
            return self.name

irc_bot/bot/forms.py
from django import forms

class getDate(forms.Form):
    date = forms.DateField()

irc_bot/bot/views.py
from irc_bot.bot.models import *
from irc_bot.bot.forms import *
from django.template.response import TemplateResponse
from datetime import datetime, timedelta
def logPage(request):
    if request.method == 'POST':
        form = getDate(request.POST)
        if form.is_valid():
            date = form.cleaned_data['date']
            entered_date = date
            current_date = datetime.now().date()
            if entered_date > current_date:
                error = 'How would I know future? o.O'
                temp = {'form': form,'error': error}
                return TemplateResponse(request, 'bot/getdate.html',temp)
            else:
                midnight = datetime(date.year, date.month, date.day)
                dayafter = datetime(date.year, date.month, date.day) + timedelta(hours=24)
                log = main.objects.filter(time__gte=midnight, time__lt=dayafter)
                if log:
		    temp = {'log': log,'date': date}
                    return TemplateResponse(request,'bot/showlog.html', temp)
                else:
                    error = 'No records found'
                    temp = {'form': form,'error': error}
                    return TemplateResponse(request, 'bot/getdate.html',temp)
        else:
            form = getDate()
            temp = {'form': form,'error': 'invalid value'}
            return TemplateResponse(request, 'bot/getdate.html',temp)
    else:
        form = getDate()
        temp = {'form': form}
        return TemplateResponse(request, 'bot/getdate.html',temp)

irc_bot/templates/base.html
{% load i18n %}
<!--[if IE 7 ]>    <html class="ie7 oldie"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8 oldie"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html> <!--<![endif]-->


<!-- menu -->
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <script src="{{STATIC_URL}}/jQuery-Form-Validator/form-validator/jquery.form-validator.min.js"></script>
       <link rel="stylesheet" type="text/css" media="screen" href="{{STATIC_URL}}/css/style.css" />
    <script type="text/javascript" src="{{STATIC_URL}}/js/jquery.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}/js/menu.js"></script>

<link rel="stylesheet" href="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/themes/overcast/jquery.ui.all.css">
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/jquery-1.9.1.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.core.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.widget.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.button.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-blind.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-bounce.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-clip.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-drop.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-fold.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-slide.js"></script>
	<script src="{{STATIC_URL}}/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.datepicker.js"></script>
	<link rel="stylesheet" href="../demos.css">
{% block title %}
{% endblock %}
<script>
$(function() {
$( "#id_date" ).datepicker({

changeMonth: true,
changeYear: true,dateFormat:'yy-mm-dd'
});
$( "#id_date" ).datepicker( "option", "showAnim", 'clip' );
});

  </script>
</head>
<body>
{% block form %}
{% endblock %}

{% block content %}

 {% endblock %}

		<!-- END content -->



</body>
</html>

irc_bot/templates/bot/getdate.html
{% extends "base.html" %}
<html>
<head>
{% block title %}
<title>GD IRC</title>
{% endblock %}
</head>
{% block form %}
<div class="header">
<p><b>GD</b> IRC bot</p>
</div>
<div class="image-place">
<img src="{{STATIC_URL}}/images/robot.png" width="350" height="250">
</div>
<div class="getDate">
<form class="getDateForm" action="" method="post">
	{% csrf_token %}
        <table>
            <tr><th><label for="id_date"></label></th><td><input id="id_date" name="date" type="text" placeholder="Enter date"/></td></tr>
						{% if error %}
						<span class="error">{{ error }}</span>
						{% endif %}
        </table>
<br><br>
       <input id="gobutton" type="submit" value="Submit" />
    </form>
</div>
{% endblock %}
</html>

irc_bot/templates/bot/showlog.html
{% extends "base.html" %}
<html>
<head>
{% block title %}
<title>GD IRC</title>
{% endblock %}
</head>
{% block content %}
<a href="{{LOCAL_URL}}/irc_bot">
<img src="{{ LOCAL_URL }}/irc_static/images/Flaticon_340.png" width="40" height="30">
</a>
<div class="log-date">
<p> Logs for {{ date }} </p>
</div>
{% if log %}
<table border='1'>
<tr>
	<th>Time</th>
	<th>Name</th>
	<th>Message</th>
</tr>
{% for values in log %}
<tr>
	{% if values.type != 'part' %}
		<td id='time'>{{ values.time|time:"H:i" }}</td>
		<td id='name'>{{ values.name }}</td>
		{% if values.type == 'pubmsg' %}
			<td id='message-pubmsg'>{{ values.message }}</td>
		{% elif values.type == 'join' %}
			<td id='message-join'>{{ values.name }} got into IRC</td>
		{% elif values.type == 'quit' %}
			<td id='message-quit'>{{ values.message }}</td>
		{% elif values.type == 'action' %}
			<td id='message-action'>**{{ values.message }}**</td>
		{% elif values.type == 'nick' %}
			<td id='message-action'>nick --> {{ values.message }}</td>
		{% elif values.type == 'topic' %}
			<td id='message-action'>{{ values.message }}</td>
		{% endif %}
	{% else %}
		<td id='time'>{{ values.time|time:"H:i" }}</td>
		<td id='name'>{{ values.name }}</td>
		{% if values.message %}
			<td id='message-quit'>{{ values.message }}</td>
		{% else %}
			<td id='message-quit'>"Leaving"</td>
		{% endif %}
	{% endif %}
</tr>
{% endfor %}
{% endif %}
</table>
{% endblock %}
</html>